services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Docker/Dockerfile
    restart: unless-stopped
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/home/pn/app/
    ports:
      - 3000:3000
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Docker/Dockerfile
    restart: unless-stopped
    command: npm start
    volumes:
      - ./frontend:/home/usr/app/
    ports:
      - 4000:4000
